version: '3'
services:
  clickhousedb:
    image: clickhouse/clickhouse-server
    container_name: clickhousedb
    volumes:
      - ai_image_search_data:/var/lib/clickhouse
      - ./clickhouseinit.sql:/docker-entrypoint-initdb.d/clickhouseinit.sql
    ports:
      - 127.0.0.1:8123:8123
      - 127.0.0.1:9000:9000
    networks:
      - clickhouse-net
    env_file:
      - .env

networks:
  clickhouse-net:

volumes:
  ai_image_search_data:
    driver: local
  
secrets:
  clickhouse_password:
    file: clickhouse_password.txt